alias cls="clear"
alias apti="sudo apt-get install "
alias upgrade="sudo apt-get update && sudo apt-get upgrade"
alias update="sudo apt-get update"
alias hadet="rm "
alias hallo="touch "
alias commit="git commit -a"
