#!/bin/bash
set -euo pipefail

# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# load brew into current shell for subsequent installs
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# packages
brew install gh
